spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: PaymentDB
server:
  port: 8082
      
    
#spring.data.mongodb.uri=mongodb+srv://root:<password>@cluster0.eekpb.mongodb.net/PaymentDB?retryWrites=true&w=majority
#spring.data.mongodb.database=paymentDB