spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: PaymentDB
# spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://root:<root>@cluster0.eekpb.mongodb.net/PaymentDB?retryWrites=true&w=majority
#      database: PaymentDB
server:
  port: 8082
    